services:
  db:
    container_name: hackaton_backend
    image: postgres:16.3
    restart: always
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hackatondb

